name: go-build-binary

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build binary
      uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.github_token }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.16
