name: golang-ci

on: [push, pull_request]

jobs:
  lint:
    name: runner / lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Linting golang code
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}

  ubuntu-test:
    name: runner / ubuntu-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Run golang tests
        run: go test oslayer

  darwin-test:
    name: runner / darwin-test
    runs-on: macos-11
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2
    
      - name: Run golang tests
        run: go test oslayer
