name: golang-ci

on: [push, pull_request]

jobs:
  lint:
    name: runner / lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Linting golang code
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}

  ubuntu-latest-test:
    name: runner / ubuntu-latest-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Run golang tests
        run: sudo go test -race -count 10 oslayer

  ubuntu-18.04-test:
    name: runner / ubuntu-18.04-test
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Run golang tests
        run: sudo go test -race -count 10 oslayer

  darwin-test:
    name: runner / darwin-test
    runs-on: macos-11
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2
    
      - name: Run golang tests
        run: go test -race -count 10 oslayer

  integration-test-ubuntu-latest:
    name: runner / integration-test-ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Run integrational tests
        run: ./integration-test.sh

  integration-test-ubuntu-18.04:
    name: runner / integration-test-ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Run integrational tests
        run: ./integration-test.sh
  
  integration-test-darwin:
    name: runner / integration-test-darwin
    runs-on: macos-11
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Run integrational tests
        run: ./integration-test.sh