
name: new-release

on:
  push:
    branches: [ main ]

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create release
      id: create_release
      uses: actions/create-release@v1